name: eureka-service
server:
  port: 10086
spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
