name: user-service
server:
  port: 8080
  servlet:
    context-path: /user
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
  application:
    name: user-service

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  mapper-locations: classpath*:mapper/*.xml #MyBatis映射文件的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印


jwt:
  header: Authorization
  secret: 12345678
  expiration: 10000000
